apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
        type: frontend
    spec:
      containers:
      - name: node-app
        image: moustafasaber36/my-node-app:final
        ports:
        - name: http
          containerPort: 3000